[project]
name = "Estimates-Program"
version = "0.0.0" # Not used, refer to config.yml instead
requires-python = ">=3.11"
dependencies = [
    "cerberus",
    "mssql",
    "numpy",
    "pandas",
    "polars",
    "pyodbc",
    "pyyaml",
    "sqlalchemy",
    "toml",
]
